## Version 2024/01/01 — Lunch Match subdomain conf für SWAG
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name lunchmatch.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        # Matches container_name of the web service in deploy/docker-compose.yml.
        set $upstream_app lunchmatch;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
